// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol"; //interface for interacting with equity tokens
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol"; // Cryptographic library for recovering wallet addresses from signatures
import "@openzeppelin/contracts/utils/cryptography/EIP712.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

contract EquitySecondaryMarketplace is EIP712, ReentrancyGuard, Ownable {
    using ECDSA for bytes32;

    uint256 public platformFeeBps = 200; // 2% fee
    address public feeTreasury;

    // Address of your backend server that processes Didit webhooks
    address public kycSignerAddress;

    // EIP-712 TypeHashes
    bytes32 private constant ORDER_TYPEHASH = keccak256(
        "Order(address seller,address tokenAddress,uint256 tokenAmount,uint256 pricePerToken,uint256 nonce,uint256 expiry)"
    );

    bytes32 private constant KYC_TYPEHASH = keccak256(
        "KycVerification(address buyer,address seller,uint256 deadline)"
    );

    mapping(address => mapping(uint256 => bool)) public isNonceInvalidated; // Tracks used or canceled order nonces to prevent double-spending and replay attacks.

    event OrderFilled(
        bytes32 indexed orderHash,
        address indexed seller,
        address indexed buyer,
        address tokenAddress,
        uint256 tokenAmount,
        uint256 totalPrice,
        uint256 platformFee
    );
    event OrderCancelled(address indexed seller, uint256 indexed nonce);
    event KycSignerUpdated(address newSigner);

    constructor(
        address _feeTreasury,
        address _kycSignerAddress
    ) EIP712("EquityMarketplace", "1") Ownable(msg.sender) {
        require(_feeTreasury != address(0), "Invalid treasury");
        require(_kycSignerAddress != address(0), "Invalid KYC signer");
        feeTreasury = _feeTreasury;
        kycSignerAddress = _kycSignerAddress;
    }

    /**
     * main trade function to fill an order on the secondary marketplace
     * @notice Fill order with Off-Chain Didit Server KYC verification
     * @param kycDeadline Expiry time for the backend KYC authorization ticket
     * @param kycSignature Signature generated by your backend confirming Didit approval
     */
    function fillOrder(
        address seller,
        address tokenAddress,
        uint256 tokenAmount,
        uint256 pricePerToken,
        uint256 nonce,
        uint256 expiry,
        bytes calldata sellerOrderSignature,
        uint256 kycDeadline,
        bytes calldata kycSignature
    ) external payable nonReentrant {
        // 1. Time & Nonce Validity
        require(block.timestamp <= expiry, "Order expired");
        require(!isNonceInvalidated[seller][nonce], "Order already filled or cancelled");

        // 2. Off-Chain KYC Authorization Check (Didit Server Signature)
        require(block.timestamp <= kycDeadline, "KYC authorization expired");
        bytes32 kycStructHash = keccak256(
            abi.encode(KYC_TYPEHASH, msg.sender, seller, kycDeadline)
        );
        bytes32 kycHash = _hashTypedDataV4(kycStructHash);
        address recoveredKycSigner = ECDSA.recover(kycHash, kycSignature);
        require(recoveredKycSigner == kycSignerAddress, "Invalid KYC authorization");

        // 3. Price & Value Calculation
        uint256 totalPrice = (tokenAmount * pricePerToken) / 1e18;
        require(msg.value >= totalPrice, "Insufficient ETH sent");

        // 4. Verify Seller Order Signature (EIP-712)
        bytes32 orderStructHash = keccak256(
            abi.encode(ORDER_TYPEHASH, seller, tokenAddress, tokenAmount, pricePerToken, nonce, expiry)
        );
        bytes32 orderHash = _hashTypedDataV4(orderStructHash);
        address recoveredSeller = ECDSA.recover(orderHash, sellerOrderSignature);
        require(recoveredSeller == seller, "Invalid seller signature");

        // 5. Invalidate Nonce
        isNonceInvalidated[seller][nonce] = true;

        // 6. Calculate Fees
        uint256 feeAmount = (totalPrice * platformFeeBps) / 10000;
        uint256 sellerPayout = totalPrice - feeAmount;

        // 7. Execute Transfers
        if (feeAmount > 0) {
            (bool feeSuccess, ) = payable(feeTreasury).call{value: feeAmount}("");
            require(feeSuccess, "Fee transfer failed");
        }

        (bool sellerSuccess, ) = payable(seller).call{value: sellerPayout}("");
        require(sellerSuccess, "Seller payout failed");

        // Transfer ERC-20 Equity Tokens
        IERC20(tokenAddress).transferFrom(seller, msg.sender, tokenAmount);

        // Refund excess ETH
        if (msg.value > totalPrice) {
            payable(msg.sender).transfer(msg.value - totalPrice);
        }

        emit OrderFilled(orderHash, seller, msg.sender, tokenAddress, tokenAmount, totalPrice, feeAmount);
    }

    function cancelOrder(uint256 nonce) external {
        require(!isNonceInvalidated[msg.sender][nonce], "Nonce already invalidated");
        isNonceInvalidated[msg.sender][nonce] = true;
        emit OrderCancelled(msg.sender, nonce);
    }

    // ── Admin Functions ──
    function setKycSignerAddress(address _newSigner) external onlyOwner {
        require(_newSigner != address(0), "Invalid address");
        kycSignerAddress = _newSigner;
        emit KycSignerUpdated(_newSigner);
    }
}