import { expect } from "chai";
import { ethers, network } from "hardhat";
import { SignerWithAddress } from "@nomicfoundation/hardhat-ethers/signers";
import { BigNumberish , Contract, ContractFactory , ContractTransactionResponse } from "ethers";

describe("FundXProut Full Lifecycle Testing", function () {
  let CampaignFactory: ContractFactory;
  let factory: Contract & any;
  let campaignContract: Contract & any;
  let tokenContract: Contract & any;
  
  let deployer: SignerWithAddress;
  let startupOwner: SignerWithAddress;
  let investor: SignerWithAddress;

  beforeEach(async function () {
    // 1. Get different signers with correct TypeScript types
    [deployer, startupOwner, investor] = await ethers.getSigners();

    // 2. Deploy the master Factory contract
    CampaignFactory = await ethers.getContractFactory("CampaignFactory");
    factory = await CampaignFactory.connect(deployer).deploy();
    await factory.waitForDeployment();
  });

  it("Should lock tokens in escrow during campaign and allow claiming post-success", async function () {
    // Parameters for our test campaign
    const campaignName: string = "Rise of Nexus";
    const tokenSymbol: string = "RON";
    const fundingGoal: BigNumberish = ethers.parseEther("5"); // 5 ETH target
    const durationInDays: number = 30;
    const pricePerToken: BigNumberish = ethers.parseEther("0.1"); // 1 token = 0.1 ETH

    // --- STEP 1: LAUNCH THE CAMPAIGN VIA FACTORY ---
    const tx = await factory.connect(startupOwner).createCampaign(
      campaignName,
      tokenSymbol,
      fundingGoal,
      durationInDays,
      pricePerToken
    );
    const receipt = await tx.wait();

    // Parse out the addresses generated by the factory event
    const event = receipt.logs.find((x: any) => x.fragment?.name === "CampaignCreated") as any;
    const campaignAddress: string = event.args.campaignAddress;
    const tokenAddress: string = event.args.tokenAddress;

    // Attach local Javascript contract instances to those deployed addresses
    campaignContract = await ethers.getContractAt("BusinessCampaign", campaignAddress);
    tokenContract = await ethers.getContractAt("EquityToken", tokenAddress);

    // --- STEP 2: INVESTOR CONTRIBUTES ---
    // The investor wants to buy 20 tokens, costing 2 ETH (20 * 0.1 ETH)
    const investmentAmount: BigNumberish = ethers.parseEther("2");
    
    await expect(
      campaignContract.connect(investor).contribute({ value: investmentAmount })
    ).to.emit(campaignContract, "Contribution");

    // ✅ NEW ESCROW CHECK A: Verify investor's wallet balance is 0 right now
    const interimTokenBalance: BigNumberish = await tokenContract.balanceOf(investor.address);
    expect(interimTokenBalance).to.equal(0); 

    // ✅ NEW ESCROW CHECK B: Verify the contract recorded what they are owed internally
    const expectedTokens: BigNumberish = ethers.parseEther("20");
    const escrowedAmount: BigNumberish = await campaignContract.tokenEscrowBalances(investor.address);
    expect(escrowedAmount).to.equal(expectedTokens);

    // --- STEP 3: HIT TARGET GOAL ---
    // Investor sends another 3 ETH to cross the 5 ETH target pool goal
    await campaignContract.connect(investor).contribute({ value: ethers.parseEther("3") });

    // --- STEP 4: FAST-FORWARD TIME PAST DEADLINE ---
    const durationInSeconds: number = durationInDays * 24 * 60 * 60;
    await network.provider.send("evm_increaseTime", [durationInSeconds + 1]);
    await network.provider.send("evm_mine"); 

    // --- STEP 5: FINALIZE ---
    await campaignContract.connect(startupOwner).finalize();

    // --- STEP 6: INVESTOR CLAIMS TOKENS FROM ESCROW ---
    // Now that state is Funded, investor triggers the transfer to their wallet
    await expect(
      campaignContract.connect(investor).claimTokens()
    ).to.not.be.reverted;

    // ✅ NEW ESCROW CHECK C: Balance should now be inside their wallet (50 tokens total)
    const totalExpectedTokens: BigNumberish = ethers.parseEther("50");
    const finalInvestorTokenBalance: BigNumberish = await tokenContract.balanceOf(investor.address);
    expect(finalInvestorTokenBalance).to.equal(totalExpectedTokens);

    // --- STEP 7: OWNER WITHDRAWAL ---
    const ownerBalanceBefore: BigNumberish = await ethers.provider.getBalance(startupOwner.address);

    const withdrawTx = await campaignContract.connect(startupOwner).withdrawFunds();
    const withdrawReceipt = await withdrawTx.wait();
    
    const gasUsed = withdrawReceipt.gasUsed * withdrawReceipt.gasPrice;

    const finalContractBalance: BigNumberish = await ethers.provider.getBalance(campaignAddress);
    expect(finalContractBalance).to.equal(0);

    const ownerBalanceAfter: BigNumberish = await ethers.provider.getBalance(startupOwner.address);
    expect(ownerBalanceAfter).to.be.greaterThan(ownerBalanceBefore);
  });
});